name: Spell check

on:
  pull_request:
    branches:
      - '**'
concurrency:
  group: spell-check-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
      - name: Spell check
        run: npx cspell "**/*.{ts,tsx}"
